# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
use-bioc: true
bioc-required: true
bioc_packages: BiocInstaller
sudo: false
cache: packages

